FROM php:8.0-fpm

RUN apt-get update
RUN apt-get upgrade -y
RUN apt-get install -y --no-install-recommends \
    vim debconf apt-transport-https apt-utils  build-essential locales acl mailutils \
    wget zip unzip gnupg gnupg1 gnupg2 less cron apt-transport-https apt-utils \
    build-essential locales acl pv htop g++ \
    libbz2-dev libc-client-dev libcurl4-gnutls-dev libedit-dev libfreetype6-dev \
    libicu-dev libjpeg62-turbo-dev libkrb5-dev libldap2-dev libldb-dev libmagickwand-dev \
    libmcrypt-dev libmemcached-dev libpng-dev libpq-dev libsqlite3-dev libssl-dev \
    libreadline-dev libxslt1-dev libzip-dev memcached zlib1g-dev gcc make autoconf \
    libc-dev pkg-config libmcrypt-dev libonig-dev procps acl

RUN docker-php-ext-install bcmath
RUN docker-php-ext-install bz2
RUN docker-php-ext-install calendar
RUN docker-php-ext-install exif
RUN docker-php-ext-install gettext
RUN docker-php-ext-install opcache
RUN docker-php-ext-install mysqli
RUN docker-php-ext-install pdo_mysql
RUN docker-php-ext-install soap
RUN docker-php-ext-install sockets
RUN docker-php-ext-install xsl
RUN docker-php-ext-install zip
RUN docker-php-ext-configure zip
RUN docker-php-ext-configure gd --enable-gd --with-freetype --with-jpeg --with-webp && docker-php-ext-install gd
RUN docker-php-ext-configure imap --with-kerberos --with-imap-ssl && docker-php-ext-install imap
RUN docker-php-ext-configure intl
RUN docker-php-ext-install intl
RUN docker-php-ext-configure ldap
RUN docker-php-ext-install ldap

RUN rm -rf /tmp/pear ~/.pearrc

RUN pecl update-channels
RUN pecl install mcrypt-1.0.4 && docker-php-ext-enable mcrypt
RUN pecl install redis && docker-php-ext-enable redis
RUN pecl install xdebug && docker-php-ext-enable xdebug
RUN wget -O /usr/local/bin/phpunit https://phar.phpunit.de/phpunit-9.phar && chmod +x /usr/local/bin/phpunit

RUN mkdir -p /usr/src/php/ext/imagick; \
    curl -fsSL https://github.com/Imagick/imagick/archive/06116aa24b76edaf6b1693198f79e6c295eda8a9.tar.gz | tar xvz -C "/usr/src/php/ext/imagick" --strip 1; \
    docker-php-ext-install imagick;

RUN apt-get update && \
    apt-get -y --no-install-recommends install git && \
    php -r "readfile('http://getcomposer.org/installer');" | php -- --install-dir=/usr/bin/ --filename=composer

RUN docker-php-source delete
RUN apt-get remove -y g++ wget
RUN apt-get autoremove --purge -y && apt-get autoclean -y && apt-get clean -y
RUN rm -rf /var/lib/apt/lists/*
RUN rm -rf /tmp/* /var/tmp/*

